virt-install \
--name 'createVm' \
--ram 2048 \
--disk path=/var/lib/libvirt/images/createVm,size=20 \
--vcpus 1 \
--os-type linux \
--os-variant ubuntuprecise \
--network bridge=virbr0 \
--graphics none \
--console pty,target_type=serial \
--location 'http://jp.archive.ubuntu.com/ubuntu/dists/precise/main/installer-amd64/' \
--extra-args 'console=ttyS0' \
--noreboot