virt-install \
--name 'createVm' \
--ram 2048 \
--disk path=/var/lib/libvirt/images/createVm,size=20 \
--vcpus 1 \
--os-type linux \
--os-variant ubuntuprecise \
--network bridge=virbr0 \
--graphics none \
--location 'http://jp.archive.ubuntu.com/ubuntu/dists/precise/main/installer-amd64/' \
--initrd-inject='/directory/kickstart.ks' \
--extra-args "ks=file:/kickstart.ks console=ttyS0"
